
include:
- https://git.5th.im/lb-public/ci-template/raw/master/ci.yaml

stages:
  - build
  - push

## push canary
push_chart_canary:
  stage: push
  extends: .docker-login
  script:
  - sudo apt-get update
  - sudo apt-get install helm
  - helm registry login ${Harbor_Host} -u ${Harbor_UserName} -p ${Harbor_Password}
  - make package-chart push-chart


push_chart_prod:
  stage: push
  extends: .docker-login
  script:
  - sudo apt-get update
  - sudo apt-get install helm
  - helm registry login ${Harbor_Host} -u ${Harbor_UserName} -p ${Harbor_Password}
  - make package-chart push-chart
